# Generated by Django 5.1 on 2025-09-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='blog_thumbnails/')),
                ('author_name', models.CharField(max_length=100)),
                ('author_image', models.ImageField(upload_to='author_images/')),
            ],
        ),
    ]
