# Generated by Django 5.1 on 2025-09-28 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_rename_description_blogpost_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogphotosvideos',
            old_name='news',
            new_name='blog',
        ),
        migrations.AlterField(
            model_name='blogphotosvideos',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_photos/'),
        ),
    ]
