# Generated by Django 5.1 on 2025-10-05 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_rename_news_blogphotosvideos_blog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('project_type', models.CharField(max_length=100)),
                ('project_description', models.TextField()),
                ('project_image', models.ImageField(upload_to='project_images/')),
                ('project_long_image', models.ImageField(upload_to='project_images/')),
                ('link', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
