# Generated by Django 5.1 on 2025-10-05 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0005_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_image',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_long_image',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
    ]
