# Generated by Django 5.1 on 2025-10-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0006_alter_projects_project_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinquiry',
            name='mobile',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
